version: "3"
services:
  backend:
    container_name: backend 
    build: 
      context: ./backend
    depends_on:
      - db  
    volumes:
      - backend_data:/usr/app
    environment:  
      - MONGO_URL=mongodb://db:27017/todos
      - APP_PORT=80
    ports: 
      - '80:80'

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - frontend_data:/app
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/todos

volumes:
  backend_data:
  frontend_data:
